version: "3.8"

services:
  credit-risk-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MLFLOW_TRACKING_URI=http://your-tracking-server:5000  # Replace if using remote MLflow
